### ISSUE TITLE
Stuck on Homework 7.2

### ISSUE THREAD

**Issue by andreastedile** [giuspek/Formal-Methods-2022#10]
Though I have scrupulously watched Lab 7's recording, I (not proudly) admit I am unable to complete Homework 7.2. I am thus unable to proceed with the next lab.

The exercise reads as follows:

> Use nuXmv to create a "random" calculator: it creates two random arrays of 3 integers numbers in the range [1,10], then it randomly choose what operator apply for each pair of elements in the arrays (among sum, subtraction and multiplication) and store it in an output array of 3 elements called res.
> The results must be defined in 3 steps: in the first iteration you’ll store the random operation between elements with index 0, in the second iteration the random operation between elements with index 1 and the same for the last index.
> Use an additional variable, index, to take into account this evolution.

Here is my tentative solution:

```
MODULE main
DEFINE 
    LEN := 3;
    MIN_N := 1;
    MAX_N := 10;
FROZENVAR
    first : array 0..LEN - 1 of MIN_N..MAX_N;
    second : array 0..LEN - 1 of MIN_N..MAX_N;
    ops : array 0..LEN - 1 of {add, sub, mul};
VAR
    res : array 0..LEN - 1 of MIN_N - MAX_N..MAX_N * MAX_N;
    iter : 0..LEN - 1;
     ̶i̶ ̶:̶ ̶0̶.̶.̶L̶E̶N̶ ̶-̶ ̶2̶;̶
ASSIGN
    init(iter) := 0;
    next(iter) := min(iter + 1, LEN - 1);

    init(res[0]) := case
        ops[0] = add : first[0] + second[0];
        ops[0] = sub : first[0] - second[0];
        ops[0] = mul : first[0] * second[0];
    esac;

TRANS next(ops[iter]) = add -> next(res[iter]) = next(first[iter]) + next(second[iter]);
TRANS next(ops[iter]) = sub -> next(res[iter]) = next(first[iter]) - next(second[iter]);
TRANS next(ops[iter]) = mul -> next(res[iter]) = next(first[iter]) * next(second[iter]);

-- The update of an element of the res array persists over time
 ̶I̶N̶V̶A̶R̶ ̶i̶ ̶<̶ ̶i̶t̶e̶r̶ ̶-̶>̶ ̶r̶e̶s̶[̶i̶]̶ ̶=̶ ̶r̶e̶s̶[̶i̶t̶e̶r̶]̶;̶
-- I just realized that the line above does not implement what I have in mind.
-- The correct version would be:
TRANS iter >= 0 -> next(res[0]) = res[0];
TRANS iter >= 1 -> next(res[1]) = res[1];
TRANS iter >= 2 -> next(res[2]) = res[2];
-- How can we parametrize this?
```

The problem is that I cannot initialize the system for verification:
```
nuXmv > read_model -i Lab07/students-proposal/220930/calc-invar-only.smv
nuXmv > go ← It stucks here
```

I would deeply appreciate your guidance in this mess. What are the logical fallacies in my reasoning?

**Comment by andreastedile** [comment]
As a side note, a `FROZENVAR` array works as expected:
```
MODULE main
FROZENVAR
    arr : array 0..5 of 0..5;
```

```
nuXmv > read_model -i Lab07/students-proposal/220930/calc-simple.smv
nuXmv > go
nuXmv > pick_state -r
nuXmv > print_current_state -v
Current state is 1.1
arr[0] = 3
arr[1] = 2
arr[2] = 2
arr[3] = 2
arr[4] = 2
arr[5] = 1
nuXmv > simulate 
********  Simulation Starting From State 1.1   ********
nuXmv > print_current_state -v
Current state is 1.11
arr[0] = 3
arr[1] = 2
arr[2] = 2
arr[3] = 2
arr[4] = 2
arr[5] = 1
```

**Comment by masinag** [comment]
I was helping @andreastedile with this exercise, and I found out something I do not have a clear answer to. The solution seemed correct to me, so I tried to rewrite it in equivalent ways to look for possible bugs. 
In one on my various attemps, I found out that if I **both** move the `FROZENVAR` section below the `VAR` section **and**  the declaration of the `iter` variable above the `res` variable, the system loads immediately.
```smv
MODULE main
DEFINE 
    LEN := 3;
    MIN_N := 1;
    MAX_N := 10;

VAR
    iter : 0..LEN - 1;
    res : array 0..LEN - 1 of MIN_N - MAX_N..MAX_N * MAX_N;

FROZENVAR
    ops : array 0..LEN - 1 of {add, sub, mul};
    first : array 0..LEN - 1 of MIN_N..MAX_N;
    second : array 0..LEN - 1 of MIN_N..MAX_N;

ASSIGN
    init(iter) := 0;
    next(iter) := min(iter + 1, LEN - 1);

    init(res[0]) := case
        ops[0] = add : first[0] + second[0];
        ops[0] = sub : first[0] - second[0];
        ops[0] = mul : first[0] * second[0];
    esac;

TRANS next(ops[iter]) = add -> next(res[iter]) = next(first[iter]) + next(second[iter]);
TRANS next(ops[iter]) = sub -> next(res[iter]) = next(first[iter]) - next(second[iter]);
TRANS next(ops[iter]) = mul -> next(res[iter]) = next(first[iter]) * next(second[iter]);
TRANS iter >= 0 -> next(res[0]) = res[0];
TRANS iter >= 1 -> next(res[1]) = res[1];
TRANS iter >= 2 -> next(res[2]) = res[2];
```
<details>

<summary>which yields a correct trace</summary>

```
nuXmv > simulate -p
********  Simulation Starting From State 1.1   ********
Trace Description: Simulation Trace 
Trace Type: Simulation 
  -> State: 1.1 <-
    ops[0] = add
    ops[1] = sub
    ops[2] = mul
    first[0] = 9
    first[1] = 5
    first[2] = 5
    second[0] = 7
    second[1] = 7
    second[2] = 5
    iter = 0
    res[0] = 16
    res[1] = 20
    res[2] = -7
    MAX_N = 10
    MIN_N = 1
    LEN = 3
  -> State: 1.2 <-
    iter = 1
    res[1] = -2
    res[2] = 37
  -> State: 1.3 <-
    iter = 2
    res[2] = 25
  -> State: 1.4 <-
  -> State: 1.5 <-
  -> State: 1.6 <-
  -> State: 1.7 <-
  -> State: 1.8 <-
  -> State: 1.9 <-
  -> State: 1.10 <-
  -> State: 1.11 <-
```
</details>

In your opinion, what could the reason of this behavior be? @andreastedile suggested that it could be related to the OBDD variables ordering, which seems reasonable to me. The [NuSMV manual](https://nusmv.fbk.eu/NuSMV/userman/v26/nusmv.pdf) mentions something about that at pages 45 and 52.

**Comment by giuspek** [comment]
Hi guys, first of all, sorry about the long delay in my answer. You know, summer holidays :) 

I think your intuition is correct for the reported issue. While for most of the exercises the order does not impact too much the construction of the OBDD, there are cases where a high number of integer variables could generate this kind of problem. Adding frozenvar is a HUGE improving factor in modeling nuXmv models: if the system knows these variables, once initialized, should not be updated anymore, a lot of states would not be generated and the corresponding OBDD would be exponentially smaller; thus, every time you can use it, use it.
Moreover, when the system remains stuck on go but you feel you have written everything correctly, try to use the MathSAT-based model checking: even though we transform the problem into Bounded Model Checking, it's still helpful to see if the problem can generate some of the traces. Moreover, if you have a good guess in the number of maximum steps you need to check the property, it can really substitute the standard model checking algorithm. Of course, if you can model check the system using OBDDs, it's better :)
