### ISSUE TITLE
Possible mistake in Laboratory 8's Science modeling exercise

### ISSUE THREAD

**Issue by andreastedile** [giuspek/Formal-Methods-2022#12]
I know it is just nitpicking, but...
The third chemical reaction is `2C + O₂ → 2CO`, but [in the code](https://github.com/giuspek/Formal-Methods-2022/blob/2f32d75ae83fb9ea8945dff8fbdd351fb786ee5e/Lab08/chemical.smv#L39
) you write
`(reaction = r3) -> (next(o) = o & next(o2) = o2 - 1 & next(c) = c - 1 & next(co) = co + 2 & next(co2) = co2)`.
I have zero knowledge of chemistry, but shouldn't this be
`(reaction = r3) -> (next(o) = o & next(o2) = o2 - 1 & next(c) = c - 2 & next(co) = co + 2 & next(co2) = co2)`?

**Comment by giuspek** [comment]
Of course, you are right: I'll quickly fix the typo.
